### ISSUE TITLE
Help wanted: missing dependency

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/Geomaker#30]
Requesting vtk export I already did
```
sudo pip3 install vtk numpy-stl
```
But I currently get the error message
```
Traceback (most recent call last):
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 220, in process
    result = self.job.process(self)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 401, in process
    retval = job.process(manager, retval)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/asynchronous.py", line 355, in process
    retval = self.func(*args, **kwargs, manager=manager)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/export.py", line 165, in export_job
    return export(*args, **kwargs)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/export.py", line 187, in export
    in_coords=project.coords, out_coords=coords, resolution=resolution,
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/db.py", line 345, in generate_triangulation
    max_area=resolution**2/2,
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/export.py", line 292, in triangulate
    lib = ct.cdll.LoadLibrary(library)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtriangle-1.6.so: cannot open shared object file: No such file or directory
```
If there are any additional depencies, please specify these in the `Readme.md` or `setup.py` file

**Comment by TheBB** [comment]
See last paragraph: https://github.com/TheBB/Geomaker#dependencies

**Comment by TheBB** [comment]
Right now VTK and VTU are both just triangulated meshes, and libtriangle generates high-quality triangulations.

VTK and VTU also support quad meshes which I could make easily on my own though.

**Comment by VikingScientist** [comment]
I actually made my own `README.md` before you submitted your `readme.md` file which was my cause of confusion. You had of course addressed this already. I'll tag this as fixed and if you want to tackle the quad meshes in your last comment, the follow-up discussion can be had in #31
